//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace instagramforce.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("instagramforce.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imageDefaultProfile {
            get {
                object obj = ResourceManager.GetObject("imageDefaultProfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap instagramLogin {
            get {
                object obj = ResourceManager.GetObject("instagramLogin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;USERDATA&gt;
        ///  &lt;USER ID=&quot;8375737871000000&quot;&gt;
        ///    &lt;USERNAME&gt;SKING&lt;/USERNAME&gt;
        ///    &lt;FULLNAME&gt;Steven King&lt;/FULLNAME&gt;
        ///    &lt;PROFILEIMAGE&gt;C:\Twitter\ICON\SKING.jpg&lt;/PROFILEIMAGE&gt;
        ///    &lt;BIRTHDATE&gt;2003/06/17 00:00:00&lt;/BIRTHDATE&gt;
        ///  &lt;/USER&gt;
        ///  &lt;USER ID=&quot;7875796772726582&quot;&gt;
        ///    &lt;USERNAME&gt;NKOCHHAR&lt;/USERNAME&gt;
        ///    &lt;FULLNAME&gt;Neena Kochhar&lt;/FULLNAME&gt;
        ///    &lt;PROFILEIMAGE&gt;C:\Twitter\ICON\NKOCHHAR.jpg&lt;/PROFILEIMAGE&gt;
        ///    &lt;BIRTHDATE&gt;2005/09/21 00:00:00&lt;/BIRTHDATE&gt;
        ///  &lt;/USER&gt;
        ///  &lt;USER ID=&quot;7668697265657800&quot;&gt;
        ///    &lt;USERNAME&gt;LDEH [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string UserData {
            get {
                return ResourceManager.GetString("UserData", resourceCulture);
            }
        }
    }
}
